<?php

/**
 * @file`
 * Contains main module functions
 */

declare(strict_types = 1);

use Drupal\ckeditor5_embedded_content\ElementCallbacks;

/**
 * Implements hook_element_info_alter().
 *
 * Extends the functionality of text_format elements that have editor elements
 * attached to dynamically set the dialog selector. This allows using embedded
 * content inside embedded content 🤯.
 *
 * @see \Drupal\filter\Element\TextFormat
 * @see \editor_element_info_alter()
 */
function ckeditor5_embedded_content_element_info_alter(&$types): void {
  $types['text_format']['#pre_render'][] = [ElementCallbacks::class, 'preRenderTextFormat'];
}

/**
 * Implements hook_module_implements_alter().
 */
function ckeditor5_embedded_content_module_implements_alter(array &$implementations, string $hook): void {
  if ($hook == 'element_info_alter') {
    // Ensure we run after editor_element_info_alter().
    $group = $implementations['ckeditor5_embedded_content'];
    unset($implementations['ckeditor5_embedded_content']);
    $implementations['ckeditor5_embedded_content'] = $group;
  }
}
